### ISSUE TITLE
EBI-9008283 not expanding correctly?

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#29] opened 2015-01-26 16:32 UTC
Stoichiometry expansion perhaps isn't working correctly for EBI-9008283?
One instance of tcpz_yeast is missing its connections to tcpe_yeast?

**Comment by joshkh** [comment] 2015-01-27 12:49
I'm re-factoring the expansion method to remove our dependency on the lodash library. I'll have a look at this while I'm in there.

**Comment by joshkh** [comment] 2015-01-29 11:39
Root cause: The matrix expansion function does not account for the "otherFeatures" attribute found on interaction participants. Because of this they are left out of the process that clones participants to represent stoichiometry.

Related to issue #25 

This is now fixed and will be merged as part of the branch to remove the dependency on lodash.

**Comment by joshkh** [comment] 2015-02-06 12:23
Solved: c792dbfd0cd88d79ab759fc05f38b590d2f083b2

**Closed by joshkh** 2015-02-06 12:23 UTC
Labels: bug, in-progress
