### ISSUE TITLE
Link node label to 'home DB'

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/interaction-viewer#69] opened 2015-07-29 11:56 UTC
Hi @colin-combe,

As per our email., could you look into having a hyperlink from the node to the respective 'home DB' of the participant, e.g. UniProt/ChEBI/RNACentral? The link should be the same that's implemented for the identifier in the participant table.

Thanks,
Birgit

**Comment by colin-combe** [comment] 2015-07-29 12:24
OK, i.e. open relevant uniprot/whatever page in a new tab when node label clicked. Click needs to be on label so it doesn't interfere with expanding/collapsing bars.

The grouping of the SVG elements that make up a node needs to be changed so that the expand/collapse behaviour doesn't apply to labels.

**Comment by bmeldal** [comment] 2015-07-29 12:26
That sounds right :)

**Comment by colin-combe** [comment] 2015-08-31 11:07
OK, this is mainly done - you can test it at http://interactionviewer.org/

Two things before closing the issue and pulling it into MICommunity/interaction-viewer:
 - you say "e.g. UniProt/ChEBI/RNACentral", what others are there? Currently only Proteins, Bioactive entities, and RNA have this function.
 - the user interface could be a little annoying, with a new page opening if you click an interactor's label by mistake; let me know what you think.

Also - 
>  The link should be the same that's implemented for the identifier in the participant table.

Do you know the link in the participant table is broken for RNA's? (e.g. see http://www.ebi.ac.uk/intact/complex/details/EBI-9997373)

**Comment by bmeldal** [comment] 2015-09-01 08:22
Thanks, Colin.
Looks good. If the opening of the new page is annoying, could we make it a double-click? I'll ask Sandra when she's back tomorrow. I don't know her GH ID so can't tag her here.

As for interactor types, yes, so far only Uniprot, Chebi and RNACentral IDs. There might be gene IDs from Ensembl one day and there are definitely Ensembl IDs in the experimental data when you get round to working on the interaction viewer again. And there are internal EBI Intact ACs for molecules we had to 'make up', e.g.
http://www.ebi.ac.uk/intact/complex/details/EBI-8769041

We know the RNACentral links are broken :( We also have no idea why! Pablo and I tried to fix it in the CV file but something doesn't implement properly and we can only see if it worked with each release, i.e. have one shot at it each month (or less...). Should you have any bright idea, let us know! I think the file is still sitting in SF but as Pablo is away right now I can't ask...

**Comment by colin-combe** [comment] 2015-09-01 14:05
>  could we make it a double-click?

We could, though I recall having problems when I tried to use double-click for something similar once before - the problem is that the single click still gets fired first. It's possible, but perhaps tricky to get to work well (http://stackoverflow.com/questions/5497073/how-to-differentiate-single-click-event-and-double-click-event) .  

Right-click for this would be easy to do, but people using touch screens don't have right-click.

Long-click is another possibility, which would be available for touch screen users. We could make it either right-click or long click.

Maybe one of the usability people we have a connection with could advise?

**Comment by bmeldal** [comment] 2015-09-01 14:20
The viewer is tricky on touchscreen, I just tried it on my phone (cheap smartphone with slightly smaller screen than others...): the prod version on the CP doesn't expand, it just makes the icon disappear and displays the number (as in the actual digits) of the total length of the protein :( and the test version on your page only opens Uniprot, probably because the name_label is too close to the icon. Not sure what to do about it... What's a long click? Touch and hold?

Have you looked at the Reactome diagram? They have a '?' on the icons when you mouse-over which opens a small menu of further options. Although, mouse-over doesn't work on touchscreens either. It's tricky, all these different user technologies!

**Comment by colin-combe** [comment] 2015-09-01 14:29
> The viewer is tricky on touchscreen

We should try to get it to work nicely on touch screens, I guess we're not there yet.

> the prod version on the CP doesn't expand, it just makes the icon disappear and displays the number (as in the actual digits) of the total length of the protein :(

I think this is probably because the screen is so small, its using the amount of screen space it has to decide how to scale the length of the bar. 

> What's a long click? Touch and hold?

yes

> It's tricky, all these different user technologies!

I know... and its best to try to keep the controls as consistent as possible across the different technologies.

**Comment by bmeldal** [comment] 2015-09-01 14:41
Thanks, Colin.

Shall I ping Francis (our UX team leader) about best practice between technologies?

**Comment by colin-combe** [comment] 2015-09-09 09:54
(Thought I'd replied to this but perhaps forgot to click 'Comment' as I rushed from office...)

> Shall I ping Francis (our UX team leader) about best practice between technologies?

Yes, please do - I have been looking for advice on this for a while.

**Comment by bmeldal** [comment] 2015-09-09 10:28
Emailed Francis, I'll let you know when I have something useful :)

**Comment by bmeldal** [comment] 2015-09-16 08:30
Meeting Francis tomorrow.

**Comment by bmeldal** [comment] 2015-09-16 08:30
Btw, how do you reply in-line here? I'm blind...

**Comment by colin-combe** [comment] 2015-09-16 13:43
> Btw, how do you reply in-line here? I'm blind...

Like that you mean? If you copy/paste text then put a greater-than symbol in front of it appears indented/quoted. 

Follow that "markdown supported" link above the text box you type into for full details.

**Comment by bmeldal** [comment] 2015-09-16 15:53
Got it! Of course, I had to ctl+F in the markdown page to find where it describes quotation as I missed it by scrolling...

**Comment by bmeldal** [comment] 2015-09-17 10:28
So, after speaking to Francis this morning it looks like making the node labels interactive might be a step too far at this pt. Better to work on more pressing features and wait to hear back from our users first.
He didn't even offer a solution, he was so convinced we shouldn't focus on this right now :)

I guess we can close this issue.

Thanks for your effort, Colin,
Birgit

**Closed** 2015-09-17 10:29 UTC
