### ISSUE TITLE
Viewer incompatible with IE

### ISSUE THREAD

**Issue by joshkh** [MICommunity/interaction-viewer#78] opened 2015-11-02 13:55 UTC
The viewer makes use of the ".contains" method which is not supported by IE (tested in IE9 and IE11).

**Comment by colin-combe** [comment] 2015-11-02 15:27
> (tested in IE9 and IE11)

Yes, this does appear to be a problem. Also, the problem is present in the crosslink-viewer and I'm surprised it's never been noticed before. 

As Josh said (off GH), should be relatively straight-forward to fix. 

I'm a bit confused because all the info I have says that it has been supported in IE since version 5:
http://www.w3schools.com/jsref/met_node_contains.asp
https://developer.mozilla.org/en-US/docs/Web/API/Node/contains

Maybe IE just doesn't support it on SVG nodes? Anyway, yes, needs fixed.

**Comment by colin-combe** [comment] 2015-11-16 11:09
> should be relatively straight-forward to fix. 

I'm about to reassign this to myself and fix it? If its been fixed already let me know, otherwise I'll proceed...

**Comment by joshkh** [comment] 2015-11-16 12:14
Hi Colin,

I have a local version that I modified to work in IE. I'll locate the
changes and push a branch this afternoon.

- Josh

**Comment by joshkh** [comment] 2015-11-16 13:06
The attached pull request has arr.contains() factored out. Nothing fancy, just some more verbose loops. It looks like my editor (Atom) automatically trims excess whitespace hence all the +/- diffs. @colin-combe if that's a problem let me know and I'll revert the commit and sort out it out.

Also, I had to require d3 in NaryLink.js. I'm not sure if it has always been missing or it disappeared along the way but ultimately needed to run the built version.

**Comment by joshkh** [comment] 2015-11-16 13:07
By the way I tested this using IE11.

**Comment by colin-combe** [comment] 2015-11-16 13:26
> It looks like my editor (Atom) automatically trims excess whitespace hence all the +/- diffs. @colin-combe if that's a problem let me know and I'll revert the commit and sort out it out.

No problem, they shouldn't be there. If anything it might be useful for us all to use a similarly configured autoformatting tool.

**Comment by colin-combe** [comment] 2015-11-16 13:34
> Also, I had to require d3 in NaryLink.js. I'm not sure if it has always been missing or it disappeared along the way but ultimately needed to run the built version.

Yes, I'm not sure what's happened here either. Its like its a mistake that we used to just get away with, but don't any more.

Anyway, thanks Josh - I'll close this.

**Closed by colin-combe** 2015-11-16 13:34 UTC
Labels: bug
