### ISSUE TITLE
large complexes don't display the colour palette

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/interaction-viewer#105] opened 2016-10-05 07:10 UTC
http://www.ebi.ac.uk/intact/complex/details/EBI-1245484

is a BIG complex and doesn't show the colours when 'interactor' is selected in the legend.

And the UniProt features don't show at all (unless there aren't any for any of these participants, which I can't check).

I originally but this in the IntAct tracker but Max @tschaka1904 thinks it needs resolving on @colin-combe's end

**Comment by colin-combe** [comment] 2016-10-05 07:25
this is a duplicate of #100 

There aren't enough colours to assign a seperate colour to each interactor, the limit is 20.

If you want to remove the option for 'colour by interactor' if there are >20 then it on Max's side I think because the drop-down menu is outside the viewer.

**Comment by colin-combe** [comment] 2016-10-05 07:27
I can add a pop-up message saying "to many interactors to colour by interactor" on my side if you like

**Comment by bmeldal** [comment] 2016-10-05 07:34
Apologies, I didn't realise I' create the issue already! I do remember issues with a limited palette though.
Just checked, and the UP features are displaying so there may have been an issue with their API when I created the original ticket.

A message would help the uninitiated user :) Probably better than removing the option as user might think it's a bug.

Thanks!

**Comment by colin-combe** [comment] 2016-11-04 15:34
OK, should be fixed. I think my changes are fine so I've just merged it into the MICommunity master branch, and also published it on npm as v1.0.6.

Let me know if any problems - or if you think I'm getting too lax with regards 'due process' by just merging things into MIComunity master because I think they're fine... I can hold off and let others check things before merges if you prefer.

cheers,
c

**Closed by colin-combe** 2016-11-04 15:34 UTC

**Comment by bmeldal** [comment] 2016-11-04 15:52
Thanks, Colin. Will report back when it's been updated on your or our site :)

[removed comment from conversation, didn't realise all this email notifications related to the same thing :) ]
